//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StadiumBookingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int id { get; set; }
        public string date { get; set; }
        public string full_name { get; set; }
        public Nullable<int> hours { get; set; }
        public string earnest { get; set; }
        public string residual { get; set; }
        public string price { get; set; }
        public string mobile { get; set; }
        public Nullable<int> Stadium_Id { get; set; }
        public Nullable<int> Acc_Id { get; set; }
        public Nullable<int> Serv_Id { get; set; }
        public Nullable<int> time { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Stadiums Stadiums { get; set; }
        public virtual Services Services { get; set; }
    }
}
